version: "3.3"
services:
  # backend:
  #   build: ./
  #   image: backend
  #   container_name: backend
  #   #restart: always
  #   #network_mode: "host"
  #   ports:
  #     - 8282:8282
  #   networks:
  #     - greekkeepersnet
  #   volumes:
  #     - ./logs/:/Backend/logs/

  golang-backend:
    build: ./
    image: golang-backend
    container_name: golang-backend
    #restart: always
    #network_mode: "host"
    ports:
      - 8181:8181
    networks:
      - greekkeepersnet
    # volumes:
    #   - ./logs/:/Backend/logs/
  db:
    image: postgres:14.1-alpine
    container_name: bicas-db
    environment:
      - POSTGRES_USER=mgwdb
      - POSTGRES_PASSWORD=mgwdb
      - POSTGRES_DB=mgwdb
      - APP_DB_USER=mgwdb
      - APP_DB_PASS=mgwdb
      - APP_DB_NAME=mgwdb
    ports:
      - '5434:5434'
    networks:
      - greekkeepersnet
      # network_mode: "host"
      # volumes:
      #   - ./db-data/:/var/lib/postgresql/data
      #   - ./db_scheme/scheme.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  greekkeepersnet:
    driver: bridge
